baseURL = 'https://soratayang.github.io/'
title = '桥通软件用户手册'
theme = "github.com/google/docsy"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
enableRobotsTXT = true
enableGitInfo = true

[params]
  github_repo = "https://github.com/soratayang/soratayang.github.io"
  offlineSearch = true

[[menu.main]]
  identifier = "home"
  url = "/"
  weight = 5

[[menu.main]]
  identifier = "docs"
  url = "/docs/"
  weight = 10

# internationalization
[languages]
    [languages.zh]
        contentDir = "content/zh"
    [languages.en]
        contentDir = "content/en"
    [languages.uk]
        contentDir = "content/uk"

