baseURL = 'https://soratayang.github.io/'
title = '桥通软件用户手册' # 默认标题，会被语言特定标题覆盖
theme = "book"

languageCode = "zh-CN" # 主要语言的区域代码
defaultContentLanguage = "zh" # 默认显示内容语言
enableRobotsTXT = true
enableGitInfo = true

[params]
  BookTheme = "light" # 或 "dark", "dracula"
  BookMenuBundle = "" # 默认会从 content/docs 构建菜单，推荐保持此设置
  BookSection = "docs" # 默认从 content/docs 构建菜单，推荐保持此设置
  BookSearch = true # 启用搜索
  BookTranslatedOnly = true
  BookServiceWorker = true # 启用 Service Worker，用于离线访问和更快的加载

[[menu.main]]
  identifier = "try-now"
  name = "软件下载"
  url = "https://smp.brdi.com.cn/BSAP/qiaotong.zip"
  weight = 100

# 国际化配置
[languages]
  [languages.zh]
    title = "桥通软件用户手册" # 中文站点标题
    languageName = '中文'
    contentDir = "content/zh"
    weight = 10

  [languages.en]
    title = "Qiaotong Software User Manual" # 英文站点标题
    languageName = 'English'
    contentDir = "content/en"
    weight = 20


[markup]
  [markup.goldmark.renderer]
    unsafe = true # 允许渲染原始HTML，以便短代码如 'columns' 能正常工作
  [markup.highlight]
    noClasses = false # 确保代码高亮使用CSS类，便于自定义样式
    # 你还可以添加其他高亮配置，例如：
    # codeFences = true
    # guessSyntax = true
    # lineNos = true
    # hl_Lines = ""
    # tabWidth = 4

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'