baseURL = 'https://soratayang.github.io/'
title = '桥通软件用户手册'
theme = "github.com/alex-shpak/hugo-book"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
enableRobotsTXT = true
enableGitInfo = true

[params]
  BookTheme = "auto"
  BookToC = true
  BookSection = "docs"

[[menu.main]]
  identifier = "home"
  url = "/"
  weight = 5

[[menu.main]]
  identifier = "docs"
  url = "/docs/"
  weight = 10

[[menu.main]]
  identifier = "try-now"
  name = "软件下载"
  url = "https://smp.brdi.com.cn/BSAP/qiaotong.zip"
  weight = 100

# internationalization
[languages]
    [languages.zh]
        contentDir = "content/zh"
    [languages.en]
        contentDir = "content/en"
    [languages.uk]
        contentDir = "content/uk"

[markup]
  [markup.highlight]
    noClasses = false

